/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package imcan_managment;

import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.Image;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Font;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import static java.lang.Thread.sleep;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.MessageFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Mahmoud Sherbeny
 */
public class Student extends javax.swing.JFrame {

    /**
     * Creates new form Student
     */
    //icon
    ImageIcon error = new ImageIcon("src/Image/cancel.png");
    ImageIcon confirm = new ImageIcon("src/Image/confirm.png");

    ImageIcon back = new ImageIcon("src/Image/back.png");
    ImageIcon eback = new ImageIcon("src/Image/eback.png");

    //color
    Setting set = new Setting();

    //connection
    private Connection conn = null;
    private PreparedStatement pst = null;
    private ResultSet rs = null, rs1 = null;
    public String sql = null;

    String ssn, name, phone, course, pay, rest, day, cour, address, proid;

    int x;
    Statments st = new Statments();

    public Student() {
        initComponents();
        this.setSize(Toolkit.getDefaultToolkit().getScreenSize());
        this.setLocationRelativeTo(null);

        //set color
        jPanel1.setBackground(set.color);
        jPanel3.setBackground(set.color);

        //connection with database
        try {
            conn = DriverManager.getConnection("jdbc:mysql://localhost/imcansystem", "root", "admin");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "خطأ في الاتصال بالداتا بايز", "خطا في الداتا بايز", 0, error);
        }

        //show current time
        st.CurrentTime(currenttime);

        //show student
        st.Set_Table_Data(stutable, "select  address as 'العنوان' , phone as 'الموبيل' , name as 'الاسم' , id as 'الرقم' from student");

        //show student number
        st.Data_Number(txtnumberstudent, "SELECT count(id) FROM student", "count(id)");

        //show course
        st.Set_cmb_Data("select * from courses", cmbcours, "name");
        st.Set_cmb_Data("select * from courses", cmbcours1, "name");
        st.Set_cmb_Data("select * from courses", cmbcours2, "name");

        add_new.setVisible(false);
        edit.setVisible(false);
        show.setVisible(false);
        panelf.setVisible(true);
    }

    //get data
    private void getdata() {
        ssn = txtssn.getText();
        name = txtname.getText();
        phone = txtphone.getText();
        address = txtaddress.getText();
        course = cmbcours.getSelectedItem().toString();
        pay = txtpay.getText();
        rest = txtrest.getText();
        day = txtcoursestart.getText();
        proid = txtpariodcourse.getText();
    }

    //get data edit
    private void getdataedit() {
        ssn = txtssn1.getText();
        name = txtname1.getText();
        phone = txtphone1.getText();
        address = txtaddress1.getText();
        course = cmbcours1.getSelectedItem().toString();
        pay = txtpay1.getText();
        rest = txtrest1.getText();
        day = txtcoursestart1.getText();
        proid = txtpariodcourse1.getText();
    }

    //get data show
    private void getdatashow() {
        ssn = txtssn2.getText();
        name = txtname2.getText();
        phone = txtphone2.getText();
        address = txtaddress2.getText();
        course = cmbcours2.getSelectedItem().toString();
        pay = txtpay2.getText();
        rest = txtrest2.getText();
        day = txtcoursestart2.getText();
        proid = txtpariodcourse2.getText();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        currenttime = new javax.swing.JLabel();
        btnback = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        stutable = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        txtnumberstudent = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        txtsearch = new javax.swing.JTextField();
        rdid = new javax.swing.JRadioButton();
        rdname = new javax.swing.JRadioButton();
        btnaddnew = new javax.swing.JButton();
        btnedit = new javax.swing.JButton();
        btnprint = new javax.swing.JButton();
        btnreport = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        add_new = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtssn = new javax.swing.JTextField();
        txtname = new javax.swing.JTextField();
        txtaddress = new javax.swing.JTextField();
        txtphone = new javax.swing.JTextField();
        txtpay = new javax.swing.JTextField();
        txtcoursestart = new javax.swing.JTextField();
        txtpariodcourse = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        cmbcours = new javax.swing.JComboBox();
        txtrest = new javax.swing.JTextField();
        edit = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        txtssn1 = new javax.swing.JTextField();
        txtname1 = new javax.swing.JTextField();
        txtaddress1 = new javax.swing.JTextField();
        txtphone1 = new javax.swing.JTextField();
        txtpay1 = new javax.swing.JTextField();
        txtcoursestart1 = new javax.swing.JTextField();
        txtpariodcourse1 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        cmbcours1 = new javax.swing.JComboBox();
        txtrest1 = new javax.swing.JTextField();
        show = new javax.swing.JPanel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        txtssn2 = new javax.swing.JTextField();
        txtname2 = new javax.swing.JTextField();
        txtaddress2 = new javax.swing.JTextField();
        txtphone2 = new javax.swing.JTextField();
        txtpay2 = new javax.swing.JTextField();
        txtcoursestart2 = new javax.swing.JTextField();
        txtpariodcourse2 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        cmbcours2 = new javax.swing.JComboBox();
        txtrest2 = new javax.swing.JTextField();
        panelf = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(15, 105, 100));
        jPanel2.setPreferredSize(new java.awt.Dimension(246, 25));

        currenttime.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N

        btnback.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnback.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/back.png"))); // NOI18N
        btnback.setToolTipText("اغلق");
        btnback.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 0));
        btnback.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnbackMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnbackMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnbackMouseExited(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("الطلاب");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(currenttime, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(331, 331, 331)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnback)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(currenttime, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnback, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        stutable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        stutable.setToolTipText("بيانات الطلاب");
        stutable.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        stutable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                stutableMouseClicked(evt);
            }
        });
        stutable.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                stutableKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(stutable);

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("عدد الطلاب :");
        jLabel2.setPreferredSize(new java.awt.Dimension(74, 20));

        txtnumberstudent.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtnumberstudent.setPreferredSize(new java.awt.Dimension(74, 20));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(txtnumberstudent, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtnumberstudent, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        txtsearch.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtsearch.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtsearch.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)), "بحث", javax.swing.border.TitledBorder.RIGHT, javax.swing.border.TitledBorder.ABOVE_TOP));
        txtsearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtsearchKeyPressed(evt);
            }
        });

        rdid.setText("كود الطالب");
        rdid.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        rdid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdidActionPerformed(evt);
            }
        });

        rdname.setText("أسم الطالب");
        rdname.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        rdname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdnameActionPerformed(evt);
            }
        });

        btnaddnew.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnaddnew.setText("أضافة جديد");
        btnaddnew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddnewActionPerformed(evt);
            }
        });

        btnedit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnedit.setText("تعديل");
        btnedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditActionPerformed(evt);
            }
        });

        btnprint.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnprint.setText("طباعة");
        btnprint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnprintActionPerformed(evt);
            }
        });

        btnreport.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnreport.setText("تقرير");
        btnreport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnreportActionPerformed(evt);
            }
        });

        btndelete.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btndelete.setText("حذف");
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });

        jPanel5.setLayout(new java.awt.CardLayout());

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Add User Male_48px.png"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel4.setText("كود الطالب :");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel5.setText("أسم الطالب :");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel6.setText("رقم الموبيل :");

        jLabel30.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel30.setText("العنوان :");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel7.setText("الكورس :");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel8.setText("المدفوع :");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel10.setText("مدان :");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel11.setText("بدايت الكورس :");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("مده الكورس :");

        txtssn.setBackground(new java.awt.Color(240, 240, 240));
        txtssn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtssn.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtssn.setToolTipText("كود الطالب");
        txtssn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtname.setBackground(new java.awt.Color(240, 240, 240));
        txtname.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtname.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtname.setToolTipText("اسم الطالب");
        txtname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtaddress.setBackground(new java.awt.Color(240, 240, 240));
        txtaddress.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtaddress.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtaddress.setToolTipText("كود الطالب");
        txtaddress.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtphone.setBackground(new java.awt.Color(240, 240, 240));
        txtphone.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtphone.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtphone.setToolTipText("رقم الطالب");
        txtphone.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtphone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtphoneKeyTyped(evt);
            }
        });

        txtpay.setBackground(new java.awt.Color(240, 240, 240));
        txtpay.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtpay.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtpay.setText("0");
        txtpay.setToolTipText("كود الطالب");
        txtpay.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtpay.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtpayKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtpayKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtpayKeyTyped(evt);
            }
        });

        txtcoursestart.setBackground(new java.awt.Color(240, 240, 240));
        txtcoursestart.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtcoursestart.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtcoursestart.setToolTipText("كود الطالب");
        txtcoursestart.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtcoursestart.setEnabled(false);

        txtpariodcourse.setBackground(new java.awt.Color(240, 240, 240));
        txtpariodcourse.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtpariodcourse.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtpariodcourse.setToolTipText("كود الطالب");
        txtpariodcourse.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtpariodcourse.setEnabled(false);

        jButton1.setText("أضافة");
        jButton1.setToolTipText("اضغط لحفظ البيانات");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        cmbcours.setBackground(new java.awt.Color(240, 240, 240));
        cmbcours.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cmbcours.setToolTipText("اختر الكورس");
        cmbcours.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cmbcours.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cmbcours.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbcoursActionPerformed(evt);
            }
        });

        txtrest.setBackground(new java.awt.Color(240, 240, 240));
        txtrest.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtrest.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtrest.setToolTipText("كود الطالب");
        txtrest.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtrest.setEnabled(false);

        javax.swing.GroupLayout add_newLayout = new javax.swing.GroupLayout(add_new);
        add_new.setLayout(add_newLayout);
        add_newLayout.setHorizontalGroup(
            add_newLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(add_newLayout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, add_newLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(add_newLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(add_newLayout.createSequentialGroup()
                        .addComponent(txtrest, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                        .addGap(86, 86, 86)
                        .addComponent(jLabel10))
                    .addGroup(add_newLayout.createSequentialGroup()
                        .addGroup(add_newLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButton1)
                            .addComponent(txtssn)
                            .addComponent(txtname, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                            .addComponent(txtphone, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                            .addComponent(txtaddress, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                            .addComponent(txtpay, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                            .addComponent(txtcoursestart, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                            .addComponent(txtpariodcourse, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                            .addComponent(cmbcours, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(add_newLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(add_newLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(add_newLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel30, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGroup(add_newLayout.createSequentialGroup()
                                    .addGap(28, 28, 28)
                                    .addComponent(jLabel8)))
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(20, 20, 20))
        );
        add_newLayout.setVerticalGroup(
            add_newLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(add_newLayout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(add_newLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtssn, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(add_newLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(add_newLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(add_newLayout.createSequentialGroup()
                        .addComponent(txtphone, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(add_newLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtaddress, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(add_newLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(add_newLayout.createSequentialGroup()
                        .addComponent(cmbcours, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)
                        .addGroup(add_newLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtpay, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)))
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(add_newLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtrest, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(add_newLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtcoursestart, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(add_newLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtpariodcourse, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addGap(0, 30, Short.MAX_VALUE))
        );

        jPanel5.add(add_new, "card2");

        jLabel33.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Edit User Male_48px.png"))); // NOI18N

        jLabel34.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel34.setText("كود الطالب :");

        jLabel35.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel35.setText("أسم الطالب :");

        jLabel36.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel36.setText("رقم الموبيل :");

        jLabel37.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel37.setText("العنوان :");

        jLabel38.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel38.setText("الكورس :");

        jLabel39.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel39.setText("المدفوع :");

        jLabel40.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel40.setText("مدان :");

        jLabel41.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel41.setText("بدايت الكورس :");

        jLabel42.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel42.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel42.setText("مده الكورس :");

        txtssn1.setBackground(new java.awt.Color(240, 240, 240));
        txtssn1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtssn1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtssn1.setToolTipText("كود الطالب");
        txtssn1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtssn1.setEnabled(false);

        txtname1.setBackground(new java.awt.Color(240, 240, 240));
        txtname1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtname1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtname1.setToolTipText("اسم الطالب");
        txtname1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtaddress1.setBackground(new java.awt.Color(240, 240, 240));
        txtaddress1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtaddress1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtaddress1.setToolTipText("كود الطالب");
        txtaddress1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtphone1.setBackground(new java.awt.Color(240, 240, 240));
        txtphone1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtphone1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtphone1.setToolTipText("رقم الطالب");
        txtphone1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtphone1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtphone1KeyTyped(evt);
            }
        });

        txtpay1.setBackground(new java.awt.Color(240, 240, 240));
        txtpay1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtpay1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtpay1.setToolTipText("كود الطالب");
        txtpay1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtpay1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtpay1KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtpay1KeyTyped(evt);
            }
        });

        txtcoursestart1.setBackground(new java.awt.Color(240, 240, 240));
        txtcoursestart1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtcoursestart1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtcoursestart1.setToolTipText("كود الطالب");
        txtcoursestart1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtcoursestart1.setEnabled(false);

        txtpariodcourse1.setBackground(new java.awt.Color(240, 240, 240));
        txtpariodcourse1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtpariodcourse1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtpariodcourse1.setToolTipText("كود الطالب");
        txtpariodcourse1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtpariodcourse1.setEnabled(false);

        jButton4.setText("تعديل");
        jButton4.setToolTipText("اضغط لحفظ البيانات");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        cmbcours1.setBackground(new java.awt.Color(240, 240, 240));
        cmbcours1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cmbcours1.setToolTipText("اختر الكورس");
        cmbcours1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cmbcours1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        txtrest1.setBackground(new java.awt.Color(240, 240, 240));
        txtrest1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtrest1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtrest1.setToolTipText("كود الطالب");
        txtrest1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtrest1.setEnabled(false);

        javax.swing.GroupLayout editLayout = new javax.swing.GroupLayout(edit);
        edit.setLayout(editLayout);
        editLayout.setHorizontalGroup(
            editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editLayout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addComponent(jLabel33)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(editLayout.createSequentialGroup()
                        .addComponent(txtrest1, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                        .addGap(86, 86, 86)
                        .addComponent(jLabel40))
                    .addGroup(editLayout.createSequentialGroup()
                        .addGroup(editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButton4)
                            .addComponent(txtssn1)
                            .addComponent(txtname1, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                            .addComponent(txtphone1, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                            .addComponent(txtaddress1, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                            .addComponent(txtpay1, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                            .addComponent(txtcoursestart1, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                            .addComponent(txtpariodcourse1, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                            .addComponent(cmbcours1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel36, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel38, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel35, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel34, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel37, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGroup(editLayout.createSequentialGroup()
                                    .addGap(28, 28, 28)
                                    .addComponent(jLabel39)))
                            .addComponent(jLabel41, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel42, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(20, 20, 20))
        );
        editLayout.setVerticalGroup(
            editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editLayout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(jLabel33)
                .addGap(18, 18, 18)
                .addGroup(editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel34)
                    .addComponent(txtssn1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel35)
                    .addComponent(txtname1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(editLayout.createSequentialGroup()
                        .addComponent(txtphone1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtaddress1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(editLayout.createSequentialGroup()
                        .addComponent(cmbcours1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)
                        .addGroup(editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtpay1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel39)))
                    .addComponent(jLabel38))
                .addGap(18, 18, 18)
                .addGroup(editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel40)
                    .addComponent(txtrest1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtcoursestart1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel41))
                .addGap(18, 18, 18)
                .addGroup(editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel42, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtpariodcourse1, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton4)
                .addGap(0, 30, Short.MAX_VALUE))
        );

        jPanel5.add(edit, "card2");

        jLabel43.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel43.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Person Male_48px.png"))); // NOI18N

        jLabel44.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel44.setText("كود الطالب :");

        jLabel45.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel45.setText("أسم الطالب :");

        jLabel46.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel46.setText("رقم الموبيل :");

        jLabel47.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel47.setText("العنوان :");

        jLabel48.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel48.setText("الكورس :");

        jLabel49.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel49.setText("المدفوع :");

        jLabel50.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel50.setText("مدان :");

        jLabel51.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel51.setText("بدايت الكورس :");

        jLabel52.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel52.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel52.setText("مده الكورس :");

        txtssn2.setBackground(new java.awt.Color(240, 240, 240));
        txtssn2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtssn2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtssn2.setToolTipText("كود الطالب");
        txtssn2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtssn2.setEnabled(false);

        txtname2.setBackground(new java.awt.Color(240, 240, 240));
        txtname2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtname2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtname2.setToolTipText("اسم الطالب");
        txtname2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtname2.setEnabled(false);

        txtaddress2.setBackground(new java.awt.Color(240, 240, 240));
        txtaddress2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtaddress2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtaddress2.setToolTipText("كود الطالب");
        txtaddress2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtaddress2.setEnabled(false);

        txtphone2.setBackground(new java.awt.Color(240, 240, 240));
        txtphone2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtphone2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtphone2.setToolTipText("رقم الطالب");
        txtphone2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtphone2.setEnabled(false);

        txtpay2.setBackground(new java.awt.Color(240, 240, 240));
        txtpay2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtpay2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtpay2.setText("0");
        txtpay2.setToolTipText("كود الطالب");
        txtpay2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtpay2.setEnabled(false);

        txtcoursestart2.setBackground(new java.awt.Color(240, 240, 240));
        txtcoursestart2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtcoursestart2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtcoursestart2.setToolTipText("كود الطالب");
        txtcoursestart2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtcoursestart2.setEnabled(false);

        txtpariodcourse2.setBackground(new java.awt.Color(240, 240, 240));
        txtpariodcourse2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtpariodcourse2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtpariodcourse2.setToolTipText("كود الطالب");
        txtpariodcourse2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtpariodcourse2.setEnabled(false);

        jButton5.setText("طباعة");
        jButton5.setToolTipText("اضغط لحفظ البيانات");

        cmbcours2.setBackground(new java.awt.Color(240, 240, 240));
        cmbcours2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cmbcours2.setToolTipText("اختر الكورس");
        cmbcours2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cmbcours2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cmbcours2.setEnabled(false);

        txtrest2.setBackground(new java.awt.Color(240, 240, 240));
        txtrest2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtrest2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtrest2.setToolTipText("كود الطالب");
        txtrest2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtrest2.setEnabled(false);

        javax.swing.GroupLayout showLayout = new javax.swing.GroupLayout(show);
        show.setLayout(showLayout);
        showLayout.setHorizontalGroup(
            showLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(showLayout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addComponent(jLabel43)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, showLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(showLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(showLayout.createSequentialGroup()
                        .addComponent(txtrest2, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                        .addGap(86, 86, 86)
                        .addComponent(jLabel50))
                    .addGroup(showLayout.createSequentialGroup()
                        .addGroup(showLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButton5)
                            .addComponent(txtssn2)
                            .addComponent(txtname2, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                            .addComponent(txtphone2, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                            .addComponent(txtaddress2, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                            .addComponent(txtpay2, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                            .addComponent(txtcoursestart2, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                            .addComponent(txtpariodcourse2, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                            .addComponent(cmbcours2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(showLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(showLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(showLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel46, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel48, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel45, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel44, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel47, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGroup(showLayout.createSequentialGroup()
                                    .addGap(28, 28, 28)
                                    .addComponent(jLabel49)))
                            .addComponent(jLabel51, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel52, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(20, 20, 20))
        );
        showLayout.setVerticalGroup(
            showLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(showLayout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(jLabel43)
                .addGap(18, 18, 18)
                .addGroup(showLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel44)
                    .addComponent(txtssn2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(showLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel45)
                    .addComponent(txtname2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(showLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel46, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(showLayout.createSequentialGroup()
                        .addComponent(txtphone2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(showLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtaddress2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel47, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(showLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(showLayout.createSequentialGroup()
                        .addComponent(cmbcours2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)
                        .addGroup(showLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtpay2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel49)))
                    .addComponent(jLabel48))
                .addGap(18, 18, 18)
                .addGroup(showLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel50)
                    .addComponent(txtrest2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(showLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtcoursestart2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel51))
                .addGap(18, 18, 18)
                .addGroup(showLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel52, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtpariodcourse2, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton5)
                .addGap(0, 30, Short.MAX_VALUE))
        );

        jPanel5.add(show, "card2");

        javax.swing.GroupLayout panelfLayout = new javax.swing.GroupLayout(panelf);
        panelf.setLayout(panelfLayout);
        panelfLayout.setHorizontalGroup(
            panelfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 377, Short.MAX_VALUE)
        );
        panelfLayout.setVerticalGroup(
            panelfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 532, Short.MAX_VALUE)
        );

        jPanel5.add(panelf, "card5");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rdid, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(rdname, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtsearch))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addComponent(btndelete)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnreport)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnprint)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnedit)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnaddnew))))
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtsearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(rdid)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rdname)))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnaddnew)
                    .addComponent(btnedit)
                    .addComponent(btnprint)
                    .addComponent(btnreport)
                    .addComponent(btndelete))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1351, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 928, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnbackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnbackMouseClicked
        MainMenu log = new MainMenu();
        log.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnbackMouseClicked

    private void btnbackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnbackMouseEntered
        btnback.setIcon(eback);
    }//GEN-LAST:event_btnbackMouseEntered

    private void btnbackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnbackMouseExited
        btnback.setIcon(back);
    }//GEN-LAST:event_btnbackMouseExited

    private void rdidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdidActionPerformed
        if (rdid.isSelected()) {
            rdid.setSelected(true);
            rdname.setSelected(false);
        }
    }//GEN-LAST:event_rdidActionPerformed

    private void rdnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdnameActionPerformed
        if (rdname.isSelected()) {
            rdid.setSelected(false);
            rdname.setSelected(true);
        }
    }//GEN-LAST:event_rdnameActionPerformed

    private void btnaddnewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddnewActionPerformed
        add_new.setVisible(true);
        edit.setVisible(false);
        show.setVisible(false);
        panelf.setVisible(false);
    }//GEN-LAST:event_btnaddnewActionPerformed

    private void btneditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditActionPerformed
        if (rdname.isSelected()) {
            try {
                sql = "select * from student where name = '" + txtsearch.getText() + "'";
                pst = conn.prepareStatement(sql);
                rs = pst.executeQuery();
                if (rs.next()) {
                    sql = "select name , startday , cost , proid from courses where id = '" + rs.getString("course_id") + "'";
                    pst = conn.prepareStatement(sql);
                    rs1 = pst.executeQuery();
                    if (rs1.next()) {
                        txtssn1.setText(rs.getString("ssn"));
                        txtname1.setText(rs.getString("name"));
                        txtaddress1.setText(rs.getString("address"));
                        txtphone1.setText(rs.getString("phone"));
                        cmbcours1.setSelectedItem(rs1.getString("name"));
                        txtpay1.setText(rs.getString("pay"));
                        txtrest1.setText(String.valueOf(Integer.parseInt(rs1.getString("cost")) - Integer.parseInt(rs.getString("pay"))));
                        txtcoursestart1.setText(rs1.getString("startday"));
                        txtpariodcourse1.setText(rs1.getString("proid"));
                        x = Integer.parseInt(rs1.getString("cost"));
                    }
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "خطأ في أجراء الداتا بايز" + ex.toString(), "خطا في الداتا بايز", 0, error);
            }
        } else {
            try {
                sql = "select * from student where id = '" + txtsearch.getText() + "'";
                pst = conn.prepareStatement(sql);
                rs = pst.executeQuery();
                if (rs.next()) {
                    sql = "select name , startday , cost , proid from courses where id = '" + rs.getString("course_id") + "'";
                    pst = conn.prepareStatement(sql);
                    rs1 = pst.executeQuery();
                    if (rs1.next()) {
                        txtssn1.setText(rs.getString("ssn"));
                        txtname1.setText(rs.getString("name"));
                        txtaddress1.setText(rs.getString("address"));
                        txtphone1.setText(rs.getString("phone"));
                        cmbcours1.setSelectedItem(rs1.getString("name"));
                        txtpay1.setText(rs.getString("pay"));
                        txtrest1.setText(String.valueOf(Integer.parseInt(rs1.getString("cost")) - Integer.parseInt(rs.getString("pay"))));
                        txtcoursestart1.setText(rs1.getString("startday"));
                        txtpariodcourse1.setText(rs1.getString("proid"));
                        x = Integer.parseInt(rs1.getString("cost"));
                    }
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "خطأ في أجراء الداتا بايز" + ex.toString(), "خطا في الداتا بايز", 0, error);
            }
        }
        add_new.setVisible(false);
        edit.setVisible(true);
        show.setVisible(false);
        panelf.setVisible(false);
    }//GEN-LAST:event_btneditActionPerformed

    private void txtsearchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsearchKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (rdname.isSelected()) {                
                try {
                    st.Set_Table_Data(stutable, sql = "select  address as 'العنوان' , phone as 'الموبيل' , name as 'الاسم' , id as 'الرقم' from student where name = '" + txtsearch.getText() + "'");
                    sql = "select * from student where name = '" + txtsearch.getText() + "'";
                    pst = conn.prepareStatement(sql);
                    rs = pst.executeQuery();
                    if (rs.next()) {
                        sql = "select name , startday , cost , proid from courses where id = '" + rs.getString("course_id") + "'";
                        pst = conn.prepareStatement(sql);
                        rs1 = pst.executeQuery();
                        if (rs1.next()) {
                            txtssn2.setText(rs.getString("ssn"));
                            txtname2.setText(rs.getString("name"));
                            txtaddress2.setText(rs.getString("address"));
                            txtphone2.setText(rs.getString("phone"));
                            cmbcours2.setSelectedItem(rs1.getString("name"));
                            txtpay2.setText(rs.getString("pay"));
                            txtrest2.setText(String.valueOf(Integer.parseInt(rs1.getString("cost")) - Integer.parseInt(rs.getString("pay"))));
                            txtcoursestart2.setText(rs1.getString("startday"));
                            txtpariodcourse2.setText(rs1.getString("proid"));
                        }
                    }
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(this, "خطأ في أجراء الداتا بايز" + ex.toString(), "خطا في الداتا بايز", 0, error);
                }
            } else
            {
                st.Set_Table_Data(stutable, sql = "select  address as 'العنوان' , phone as 'الموبيل' , name as 'الاسم' , id as 'الرقم' from student where ssn = '" + txtsearch.getText() + "'");
                try {
                    sql = "select * from student where ssn = '" + txtsearch.getText() + "'";
                    pst = conn.prepareStatement(sql);
                    rs = pst.executeQuery();
                    if (rs.next()) {
                        sql = "select name , startday , cost , proid from courses where id = '" + rs.getString("course_id") + "'";
                        pst = conn.prepareStatement(sql);
                        rs1 = pst.executeQuery();
                        if (rs1.next()) {
                            txtssn2.setText(rs.getString("ssn"));
                            txtname2.setText(rs.getString("name"));
                            txtaddress2.setText(rs.getString("address"));
                            txtphone2.setText(rs.getString("phone"));
                            cmbcours2.setSelectedItem(rs1.getString("name"));
                            txtpay2.setText(rs.getString("pay"));
                            txtrest2.setText(String.valueOf(Integer.parseInt(rs1.getString("cost")) - Integer.parseInt(rs.getString("pay"))));
                            txtcoursestart2.setText(rs1.getString("startday"));
                            txtpariodcourse2.setText(rs1.getString("proid"));
                        }
                    }
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(this, "خطأ في أجراء الداتا بايز" + ex.toString(), "خطا في الداتا بايز", 0, error);
                }
            }

            add_new.setVisible(false);
            edit.setVisible(false);
            show.setVisible(true);
            panelf.setVisible(false);
        }
        if (evt.getKeyCode() == KeyEvent.VK_BACK_SPACE) {
            if (txtsearch.getText().equals("")) {
                st.Set_Table_Data(stutable, "select  address as 'العنوان' , phone as 'الموبيل' , name as 'الاسم' , id as 'الرقم' from student");
                txtssn2.setText(null);
                txtname2.setText(null);
                txtaddress2.setText(null);
                txtphone2.setText(null);
                cmbcours2.setSelectedItem(null);
                txtpay2.setText(null);
                txtrest2.setText(null);
                txtcoursestart2.setText(null);
                txtpariodcourse2.setText(null);
            }
        }
    }//GEN-LAST:event_txtsearchKeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        getdata();
        String[] items = new String[6];
        items[0] = ssn;
        items[1] = name;
        items[2] = phone;
        items[3] = address;
        items[4] = st.Result("select id from courses where name = '" + course + "'", "id");
        items[5] = pay;

        st.Insert("insert into student (ssn,name,phone,address,course_id,pay) values(?,?,?,?,?,?)", 6, items);
        st.Set_Table_Data(stutable, "select  address as 'العنوان' , phone as 'الموبيل' , name as 'الاسم' , id as 'الرقم' from student");
        st.Data_Number(txtnumberstudent, "SELECT count(id) FROM student", "count(id)");

    }//GEN-LAST:event_jButton1ActionPerformed

    private void cmbcoursActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbcoursActionPerformed
        getdata();
        if (!cmbcours.getSelectedItem().toString().equals(" ")) {
            sql = "SELECT startday , proid , cost from courses where name = '" + cmbcours.getSelectedItem().toString() + "'";
            try {
                pst = conn.prepareStatement(sql);
                rs = pst.executeQuery();
                if (rs.next()) {
                    txtcoursestart.setText(rs.getString("startday"));
                    txtpariodcourse.setText(rs.getString("proid"));
                    x = Integer.parseInt(rs.getString("cost"));
                    int y = x - Integer.parseInt(txtpay.getText());
                    txtrest.setText(String.valueOf(y));
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "خطأ في أجراء الداتا بايز" + ex.toString(), "خطا في الداتا بايز", 0, error);
            }
        }
    }//GEN-LAST:event_cmbcoursActionPerformed

    private void txtpayKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpayKeyPressed

    }//GEN-LAST:event_txtpayKeyPressed

    private void txtpayKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpayKeyTyped
        char c = evt.getKeyChar();
        if (!((c >= '0') && (c <= '9')
                || (c == KeyEvent.VK_BACK_SPACE)
                || (c == KeyEvent.VK_DELETE))) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtpayKeyTyped

    private void txtpayKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpayKeyReleased
        if (txtpay.getText().equals(null) || txtpay.getText().equals("")) {
            txtrest.setText(String.valueOf(x));
        } else {
            txtrest.setText(String.valueOf(x - Integer.parseInt(txtpay.getText())));
        }
    }//GEN-LAST:event_txtpayKeyReleased

    private void txtphoneKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtphoneKeyTyped
        char c = evt.getKeyChar();
        if (!((c >= '0') && (c <= '9')
                || (c == KeyEvent.VK_BACK_SPACE)
                || (c == KeyEvent.VK_DELETE))) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtphoneKeyTyped

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        st.Delete("delete from student where id = ?", txtsearch);
        st.Set_Table_Data(stutable, "select  address as 'العنوان' , phone as 'الموبيل' , name as 'الاسم' , id as 'الرقم' from student");
        st.Data_Number(txtnumberstudent, "SELECT count(id) FROM student", "count(id)");
    }//GEN-LAST:event_btndeleteActionPerformed

    private void stutableKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_stutableKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_DELETE) {
            st.Delete("delete from student where id = ?", txtsearch);
            st.Set_Table_Data(stutable, "select  address as 'العنوان' , phone as 'الموبيل' , name as 'الاسم' , id as 'الرقم' from student");
            st.Data_Number(txtnumberstudent, "SELECT count(id) FROM student", "count(id)");
        }
    }//GEN-LAST:event_stutableKeyPressed

    private void stutableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stutableMouseClicked
        int row = stutable.getSelectedRow();
        String t_click = (stutable.getModel().getValueAt(row, 3).toString());
        txtsearch.setText(t_click);
        add_new.setVisible(false);
        show.setVisible(true);
        edit.setVisible(false);        
        try {
            rs = st.All_Date("select * from student where id = '" + t_click + "'");
            if (rs.next()) {
                txtssn2.setText(rs.getString("ssn"));
                txtname2.setText(rs.getString("name"));
                txtaddress2.setText(rs.getString("address"));
                txtphone2.setText(rs.getString("phone"));
                cmbcours2.setSelectedItem(st.Result("select name from courses where id = '" + rs.getString("course_id") + "'", "name"));
                txtpay2.setText(rs.getString("pay"));
                txtrest2.setText(String.valueOf(Integer.parseInt(st.Result("select cost from courses where id = '" + rs.getString("course_id") + "'", "cost")) - Integer.parseInt(rs.getString("pay"))));
                txtcoursestart2.setText(st.Result("select startday from courses where id = '" + rs.getString("course_id") + "'", "startday"));
                txtpariodcourse2.setText(st.Result("select proid from courses where id = '" + rs.getString("course_id") + "'", "proid"));

            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "خطأ في أجراء الداتا بايز", "خطا في الداتا بايز", 0, error);
        }
    }//GEN-LAST:event_stutableMouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        getdataedit();
        st.update("update student set  name = '" + name + "',phone='" + phone + "',address='" + address + "',course_id = '" + st.Result("select id from courses where name = '" + cmbcours1.getSelectedItem().toString() + "'", "id") + "',pay  = '" + pay + "' where ssn = '" + ssn + "'");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void txtphone1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtphone1KeyTyped
        char c = evt.getKeyChar();
        if (!((c >= '0') && (c <= '9')
                || (c == KeyEvent.VK_BACK_SPACE)
                || (c == KeyEvent.VK_DELETE))) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtphone1KeyTyped

    private void txtpay1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpay1KeyTyped
        char c = evt.getKeyChar();
        if (!((c >= '0') && (c <= '9')
                || (c == KeyEvent.VK_BACK_SPACE)
                || (c == KeyEvent.VK_DELETE))) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtpay1KeyTyped

    private void txtpay1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpay1KeyReleased
        if (txtpay1.getText().equals(null) || txtpay1.getText().equals("")) {
            txtrest1.setText(String.valueOf(x));
        } else {
            txtrest1.setText(String.valueOf(x - Integer.parseInt(txtpay1.getText())));
        }
    }//GEN-LAST:event_txtpay1KeyReleased

    private void btnreportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnreportActionPerformed
        String[] item = new String[4];
        item[0] = "ssn";
        item[1] = "name";
        item[2] = "phone";
        item[3] = "address";

        st.report("SELECT address ,phone ,name,ssn  FROM student", "Report", "src/Image/Person Male_48px.png", "Imcan Student", item);
    }//GEN-LAST:event_btnreportActionPerformed

    private void btnprintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnprintActionPerformed
        st.Print(stutable, "Student Data", "page 1");
    }//GEN-LAST:event_btnprintActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Student().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel add_new;
    private javax.swing.JButton btnaddnew;
    private javax.swing.JLabel btnback;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnedit;
    private javax.swing.JButton btnprint;
    private javax.swing.JButton btnreport;
    private javax.swing.JComboBox cmbcours;
    private javax.swing.JComboBox cmbcours1;
    private javax.swing.JComboBox cmbcours2;
    private javax.swing.JLabel currenttime;
    private javax.swing.JPanel edit;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel panelf;
    private javax.swing.JRadioButton rdid;
    private javax.swing.JRadioButton rdname;
    private javax.swing.JPanel show;
    private javax.swing.JTable stutable;
    private javax.swing.JTextField txtaddress;
    private javax.swing.JTextField txtaddress1;
    private javax.swing.JTextField txtaddress2;
    private javax.swing.JTextField txtcoursestart;
    private javax.swing.JTextField txtcoursestart1;
    private javax.swing.JTextField txtcoursestart2;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtname1;
    private javax.swing.JTextField txtname2;
    private javax.swing.JLabel txtnumberstudent;
    private javax.swing.JTextField txtpariodcourse;
    private javax.swing.JTextField txtpariodcourse1;
    private javax.swing.JTextField txtpariodcourse2;
    private javax.swing.JTextField txtpay;
    private javax.swing.JTextField txtpay1;
    private javax.swing.JTextField txtpay2;
    private javax.swing.JTextField txtphone;
    private javax.swing.JTextField txtphone1;
    private javax.swing.JTextField txtphone2;
    private javax.swing.JTextField txtrest;
    private javax.swing.JTextField txtrest1;
    private javax.swing.JTextField txtrest2;
    private javax.swing.JTextField txtsearch;
    private javax.swing.JTextField txtssn;
    private javax.swing.JTextField txtssn1;
    private javax.swing.JTextField txtssn2;
    // End of variables declaration//GEN-END:variables
}
